Repository nimblehq/github-action-runner-android, pull requests merged in 2021-08, with the labels that each got.

#10 Set up self-hosted runner
  .github/workflows/lint_and_unit_test.yml
Labels: type : chore

#11 Implement UI tests execution into GitHub action workflow
  .github/workflows/lint_and_unit_test.yml
  .github/workflows/ui_test.yml
Labels: type : feature

#13 Bring back AVD caching
  .github/workflows/lint_and_unit_test.yml
  .github/workflows/ui_test.yml
Labels: type : chore

#14 Restructure workflows
  .github/workflows/code_analysis_and_unit_tests.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/ui_test.yml
Labels: type : chore

#15 [chore] Add `README` to the project
  README.md
Labels: type : chore

#18 Fix UI tests failed when run multiple UI test jobs simultaneously
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
Labels: type : bug

#21 [chore] Reset the version name for this repository to 1.0.0
  build.gradle
Labels: type : chore
